name: YAML validation

on:
  push:
    paths:
      - 'elements/**/*.yaml'
      - 'events/**/*.yaml'
      - 'functions/**/*.yaml'
      - 'schemas/**/*.yaml'
  pull_request:
    paths:
      - 'elements/**/*.yaml'
      - 'events/**/*.yaml'
      - 'functions/**/*.yaml'
      - 'schemas/**/*.yaml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Run validator
        run: |
          chmod +x tools/yajsv tools/validate.sh
          tools/validate.sh
